# Generated by Django 3.2.23 on 2026-04-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_auto_20260402_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='registre',
            name='date_seance',
            field=models.TextField(blank=True, null=True, verbose_name='Dates sélectionnées'),
        ),
        migrations.DeleteModel(
            name='RegistreDate',
        ),
    ]
