# Generated by Django 3.2.23 on 2026-06-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaildocument',
            name='activites',
            field=models.ManyToManyField(help_text='Sélectionnez une ou plusieurs activités dans la liste.', related_name='document_activites', to='core.Activite', verbose_name='Activités'),
        ),
        migrations.AlterField(
            model_name='portaildocument',
            name='structure',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure'),
            preserve_default=False,
        ),
    ]
