# Generated by Django 3.2.23 on 2026-06-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0242_auto_20260402_1505'),
        ('core', '0243_auto_20260616_1044'),
    ]

    operations = [
    ]
