# Generated by Django 3.2.23 on 2026-04-02 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0243_auto_20260402_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_presence', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('individu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.individu')),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registre')),
            ],
        ),
    ]
