# Generated by Django 3.2.23 on 2026-06-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0245_auto_20260630_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptaoperation',
            name='observation',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Libellé'),
        ),
        migrations.AddField(
            model_name='comptaoperation',
            name='pointage',
            field=models.BooleanField(default=False, verbose_name='Opération pointée'),
        ),
    ]
