# Generated by Django 3.2.23 on 2026-06-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0246_auto_20260630_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptaoperation',
            name='observation',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Remarque'),
        ),
    ]
