# Generated by Django 3.2.23 on 2026-08-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0248_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typededuction',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.structure', verbose_name='Structure associée'),
        ),
    ]
