name: Run Pytest

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libcairo2-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers and OS Dependencies
        run: python -m playwright install --with-deps

      - name: Test with pytest
        working-directory: ./noethysweb
        run: |
          HEADLESS=1 pytest --junitxml=pytest.xml --cov-report=term-missing --cov=. | tee pytest-coverage.txt

      - name: Post Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./noethysweb/pytest-coverage.txt
          junitxml-path: ./noethysweb/pytest.xml
